
name: nossas-faturas

services:
  app:
    build: ./app-desafio
      context: ./app-nossas-faturas
      dockerfile: Dockerfile
    volumes:
      - ./app-nossas-faturas:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    ports:
      - "5173:5173"

  api:
    build:
      context: ./api-nossas-faturas
      dockerfile: Dockerfile
    volumes:
      - ./api-nossas-faturas:/app
      - api_node_modules:/app/node_modules
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB} 
      DB_DIALECT: postgres
      TZ: America/Sao_Paulo
      SECRET_JWT: Cm7/yP8kHiJTDQCYcdQhlRZJRcj/FpAUzF/x+oxOsyKovGGie6Mq+wETRiYL78uVTZmaSz3VTPx6grMHTr9JhA==
    ports:
      - "3001:3000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    volumes: 
      - pg_data:/var/lib/postgresql/data
      - ./init_script_db:/docker-entrypoint-initdb.d
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "5432:5432"
volumes:
  app_node_modules:
  api_node_modules:
  pg_data: